### ISSUE TITLE
Doesn't work on linux

### ISSUE THREAD

**Issue by chicken-suop** [Explosion-Scratch/firebuilder#2]
```
❯ git clone https://github.com/Explosion-Scratch/firebuilder
Cloning into 'firebuilder'...
remote: Enumerating objects: 180, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 180 (delta 3), reused 10 (delta 3), pack-reused 169 (from 1)
Receiving objects: 100% (180/180), 146.44 MiB | 13.88 MiB/s, done.
Resolving deltas: 100% (53/53), done.
Updating files: 100% (89/89), done.

~ took 15s 
❯ cd firebuilder

firebuilder on  main via 🥟 v1.1.17 via  v20.11.1 
❯ bun cli.js
error: FileNotFound while resolving package "inquirer" from "/home/elliot/firebuilder/cli.js"

Bun v1.1.17 (Linux x64 baseline)

firebuilder on  main via 🥟 v1.1.17 via  v20.11.1 
❯ bun install
bun install v1.1.17 (bb66bba1)

+ typescript@5.5.4
+ @types/bun@1.1.6
+ inquirer@10.1.8
+ meow@13.2.0

51 packages installed [3.40s]

firebuilder on  main [!] via 🥟 v1.1.17 via  v20.11.1 took 3s 
❯ bun cli.js
 98 |   {
 99 |     type: "list",
100 |     name: "extendProfile.path",
101 |     when: (a) => a.extendProfile,
102 |     message: "Choose a profile to extend",
103 |     choices: readdirSync(PROFILES_PATH)
                   ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "/home/elliot/Library/Application Support/Firefox/Profiles"

      at /home/elliot/firebuilder/cli.js:103:14

Bun v1.1.17 (Linux x64 baseline)

firebuilder on  main [!] via 🥟 v1.1.17 via  v20.11.1 
❯ bun cli.js examples/my-config/config.jsonc 
 98 |   {
 99 |     type: "list",
100 |     name: "extendProfile.path",
101 |     when: (a) => a.extendProfile,
102 |     message: "Choose a profile to extend",
103 |     choices: readdirSync(PROFILES_PATH)
                   ^
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "/home/elliot/Library/Application Support/Firefox/Profiles"

      at /home/elliot/firebuilder/cli.js:103:14

Bun v1.1.17 (Linux x64 baseline)

firebuilder on  main [!] via 🥟 v1.1.17 via  v20.11.1 
```

**Comment by gotlougit** [comment]
It seems like the path to the profile is hardcoded for a macOS setup:
https://github.com/Explosion-Scratch/firebuilder/blob/e2cbbe6237ff055f73337f190b38776d050df5a0/cli.js#L21

I ended up manually patching it to my Firefox profile path.

There is also a missing import of `existsSync` in `run.js`:
https://github.com/Explosion-Scratch/firebuilder/blob/e2cbbe6237ff055f73337f190b38776d050df5a0/run.js#L1

which is required here:
https://github.com/Explosion-Scratch/firebuilder/blob/e2cbbe6237ff055f73337f190b38776d050df5a0/run.js#L44

**Comment by Explosion-Scratch** [comment]
@gotlougit Yup, I need to configure OS specific paths. I'll get to it tomorrow probably, lots going on irl. In the meantime if you just edit those files to reference your firefox you can do that instead

**Comment by Explosion-Scratch** [comment]
Will you try again?
